# This is a basic workflow to help you get started with Actions

name:  GitHUB Action CI using gcloud-setup library

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main , dev01 ]
  pull_request:
    branches: [ main , dev01 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Set env to dev01
      if: endsWith(github.ref, '/dev01')
      run: |
        echo "Project_id=cloud-demo-02" >> $GITHUB_ENV
    - name: Set env to main
      if: endsWith(github.ref, '/main')
      run: |
       echo "Project_id=cloud-demo-339414" >> $GITHUB_ENV
    
    - uses: actions/checkout@v2  
    
    - id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}' 
      
    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'my-github-action-function01'
        runtime: 'python38'
        source_dir: 'cloud-fn-demo'
        entry_point: 'hello_world'
        project_id : '${{env.project_id}}' 

